services:
  tictactoe:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - tictactoe_data:/usr/src/app/data
    ports:
      - "8000:8000"
    working_dir: /usr/src/app
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    container_name: prometheus2
    command:
      - '--config.file=/etc/prometheus/config.yml'
    volumes:
      - ./prometheus.yml:/etc/prometheus/config.yml
      - prometheus_data:/prometheus

volumes:
  prometheus_data: { }
  grafana_data: { }
  tictactoe_data: { }