# Generated by Django 5.0.6 on 2024-05-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='moves',
            field=models.CharField(default='123456789', max_length=9),
        ),
    ]
