name: Tic tac toe CI/CD 

on:
  push:
    branches:
      - '*'
jobs:
  run-tests:
    runs-on: [ubuntu-latest]
    name: Build
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run test
      run: |
          python manage.py test
          echo "Tests worked successfully"
  
    
  
