name: Tic tac toe CI/CD 

on:
  push:
    branches:
      - '*'
env:
  LOGIN: ${{ secrets.DOCKER_LOGIN }}
  PASSWORD: ${{ secrets.DOCKER_NAME }}
jobs:
  run-tests:
    runs-on: [ubuntu-latest]
    name: Running tests
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run test
      run: |
          python manage.py test
          echo "Tests worked successfully"
  deploy:
    runs-on: [ubuntu-latest]
    name: Build
    steps:
    - name: Login to docker.io
      run: echo ${{ secrets.DOCKER_PASSWORD }} | echo ${{ secrets.DOCKER_LOGIN }}
    - uses: actions/checkout@master
  
