name: Tic tac toe CI/CD 

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/tic-tac-toe.yml
  pull_request:
    paths:
      - .github/workflows/tic-tac-toe.yml.yml
      
env:
  LOGIN: ${{ secrets.DOCKER_LOGIN }}
  PASSWORD: ${{ secrets.DOCKER_PWD }}
  NAME: ${{ secrets.DOCKER_NAME }}
  
jobs:
  test:
    runs-on: [ubuntu-latest]
    name: Running tests
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run test
      run: |
          python manage.py test
          echo "Tests worked successfully"
  build_publish_deploy:
    needs: [test]
    runs-on: [ubuntu-latest]
    name: Build
    steps:
    - name: Login to docker.io
      run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
    - uses: actions/checkout@master
    - name: Build image
      run: |
        docker build -t online-tic-tac-toe .
        docker compose build 
    - name: Push image
      run: |
        docker tag online-tic-tac-toe ${{ secrets.DOCKER_LOGIN }}/online-tic-tac-toe:latest
        docker push ${{ secrets.DOCKER_LOGIN }}/online-tic-tac-toe:latest
        docker compose push 
    - name: Deploy to Server 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PWD }}
        script: |
          echo -L "Connected successfully!!"
          # Stop the previous container
          docker stop online-tic-tac-toe || true
          # Remove the previous container
          docker rm online-tic-tac-toe || true
          # Pull the latest image
          docker pull ${{ secrets.DOCKER_LOGIN }}/online-tic-tac-toe:latest
          # Run the new container
          docker run -d --name online-tic-tac-toe -p 8000:8000 ${{ secrets.DOCKER_LOGIN }}/online-tic-tac-toe:latest
        
      
